#!/bin/bash

if [[ ! -f ~/ignore_requirements.txt ]]; then
    echo "No ignore_requirements.txt file found ~/"
fi

ignores=$(cat ~/ignore_requirements.txt | tr "\n" "|")
ignores=${ignores: : -1}
ignores=$(echo $ignores | tr -d '[:space:]')

while read line; do
    echo $line | grep -vE $ignores
done
