#!/bin/python
import os
import datetime

TMP_FILE_DIR = os.path.expanduser(os.environ['TIME_KEEPER_DIR'])
LEDGER_PATH = os.path.join(
    TMP_FILE_DIR, f"ledger_{datetime.datetime.now().month}")


def create_dict():
    working_hours = dict()
    with open(LEDGER_PATH, 'r') as ledger:
        line = ledger.readline()
        while line:
            line = line.rstrip()
            date, time = line.split(" -- ")
            if date in working_hours:
                working_hours[date].append(time)
            else:
                working_hours[date] = [time]
            line = ledger.readline()
    return working_hours


def sumDaily(working_hours):
    daily_hours = dict()
    for date in working_hours:
        hours_worked = 0
        for time in working_hours[date]:
            hours, minutes = time.split(':')
            hours_worked += int(hours)
            hours_worked += round(int(minutes)/60, 1)
        daily_hours[date] = hours_worked
    return daily_hours


out = create_dict()
daily_report = sumDaily(out)
monthly_hour_count = sum(daily_report.values())
print(round(monthly_hour_count, 1))
